// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2fBRESo4R8g1ZrHZKusaM0a_D3aHWoX0',
    appId: '1:997485029937:web:142dc1431c717deac64310',
    messagingSenderId: '997485029937',
    projectId: 'kashukart-1c389',
    authDomain: 'kashukart-1c389.firebaseapp.com',
    storageBucket: 'kashukart-1c389.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKVZDyQ_d_BHm2A7UmPEJYyhKGd9BPrdY',
    appId: '1:997485029937:android:2bc08baebfa8a667c64310',
    messagingSenderId: '997485029937',
    projectId: 'kashukart-1c389',
    storageBucket: 'kashukart-1c389.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5z-fSeNzDBIbCiumGu4oM1UXEVFK9PkE',
    appId: '1:997485029937:ios:c1993447f6f4d893c64310',
    messagingSenderId: '997485029937',
    projectId: 'kashukart-1c389',
    storageBucket: 'kashukart-1c389.firebasestorage.app',
    iosBundleId: 'com.example.practiceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5z-fSeNzDBIbCiumGu4oM1UXEVFK9PkE',
    appId: '1:997485029937:ios:c1993447f6f4d893c64310',
    messagingSenderId: '997485029937',
    projectId: 'kashukart-1c389',
    storageBucket: 'kashukart-1c389.firebasestorage.app',
    iosBundleId: 'com.example.practiceProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2fBRESo4R8g1ZrHZKusaM0a_D3aHWoX0',
    appId: '1:997485029937:web:461fe4d75170ea82c64310',
    messagingSenderId: '997485029937',
    projectId: 'kashukart-1c389',
    authDomain: 'kashukart-1c389.firebaseapp.com',
    storageBucket: 'kashukart-1c389.firebasestorage.app',
  );
}
